import { NextRequest, NextResponse } from 'next/server'
import { requireAdmin } from '@/lib/auth'
import prisma from '@/lib/db'
import { slugify } from '@/lib/utils'

export const dynamic = 'force-dynamic'

const SEED_SKILLS = [
  {
    name: 'n8n',
    slug: 'n8n',
    officialUrl: 'https://n8n.io',
    githubUrl: 'https://github.com/n8n-io/n8n',
    oneLiner: 'Open-source workflow automation tool with 400+ integrations and AI capabilities.',
    chineseSummary: 'n8n 是一款开源的工作流自动化工具，支持400多种应用集成。你可以通过可视化界面拖拽连接不同服务，实现数据在各平台间的自动流转。比如自动将邮件转为任务、定时汇总报表、触发AI分析等。对比 Zapier 更灵活，可自托管，数据不出境。适合需要打通多个工具的运营、产品和技术团队，能节省大量重复操作时间。',
    roleCategories: ['operations', 'engineering', 'marketing'],
    functionCategories: ['automation', 'mcp-agent'],
    tags: ['automation', 'workflow', 'open-source', 'self-hosted', 'no-code'],
    difficulty: 'intermediate',
    requiresCoding: false,
    isOpenSource: true,
    pricingType: 'open_source',
    stars: 45000,
    score: 92,
    isActive: true,
    isRelevant: true,
  },
  {
    name: 'Cursor',
    slug: 'cursor',
    officialUrl: 'https://cursor.sh',
    githubUrl: null,
    oneLiner: 'AI-first code editor built on VS Code with GPT-4 and Claude integration.',
    chineseSummary: 'Cursor 是专为 AI 编程打造的代码编辑器，基于 VS Code 构建，深度集成 GPT-4 和 Claude。它能理解整个代码库上下文，直接在编辑器内对话完成代码生成、重构、调试。对比 GitHub Copilot，Cursor 支持多文件编辑、全项目理解和自然语言需求描述直接生成代码。能节省程序员30-50%的编码时间，特别适合处理样板代码和API集成。',
    roleCategories: ['engineering'],
    functionCategories: ['coding', 'mcp-agent'],
    tags: ['AI coding', 'IDE', 'GPT-4', 'Claude', 'productivity'],
    difficulty: 'beginner',
    requiresCoding: true,
    isOpenSource: false,
    pricingType: 'freemium',
    stars: 0,
    score: 95,
    isActive: true,
    isRelevant: true,
  },
  {
    name: 'Perplexity AI',
    slug: 'perplexity-ai',
    officialUrl: 'https://www.perplexity.ai',
    githubUrl: null,
    oneLiner: 'AI-powered search engine that provides real-time answers with cited sources.',
    chineseSummary: 'Perplexity 是一款 AI 搜索引擎，能用自然语言提问并获得带来源引用的实时答案。它整合了多个网络来源，直接给出综合摘要，不需要你逐一打开链接。特别适合做行业调研、竞品分析、快速了解陌生领域。比 Google 快3-5倍完成信息汇总，能节省大量搜索和阅读时间。支持上传文档进行对话分析。',
    roleCategories: ['consulting', 'research', 'finance', 'marketing'],
    functionCategories: ['research-search', 'document-processing'],
    tags: ['AI search', 'research', 'real-time', 'citations'],
    difficulty: 'beginner',
    requiresCoding: false,
    isOpenSource: false,
    pricingType: 'freemium',
    stars: 0,
    score: 91,
    isActive: true,
    isRelevant: true,
  },
  {
    name: 'Gamma',
    slug: 'gamma',
    officialUrl: 'https://gamma.app',
    githubUrl: null,
    oneLiner: 'AI-powered presentation and document creator that generates slides from text prompts.',
    chineseSummary: 'Gamma 是 AI 驱动的演示文稿工具，输入主题或大纲，几秒内自动生成精美 PPT。支持从文档、网页内容直接转换成幻灯片，风格专业多样。对比传统 PowerPoint，制作一份20页 PPT 从数小时压缩到15分钟。适合咨询顾问、产品经理、市场人员快速制作汇报材料。支持在线分享，不需要安装软件。',
    roleCategories: ['consulting', 'product', 'marketing', 'management'],
    functionCategories: ['presentation', 'writing-editing'],
    tags: ['AI PPT', 'presentation', 'slides', 'no-code'],
    difficulty: 'beginner',
    requiresCoding: false,
    isOpenSource: false,
    pricingType: 'freemium',
    stars: 0,
    score: 88,
    isActive: true,
    isRelevant: true,
  },
  {
    name: 'Fireflies.ai',
    slug: 'fireflies-ai',
    officialUrl: 'https://fireflies.ai',
    githubUrl: null,
    oneLiner: 'AI meeting assistant that auto-records, transcribes, and summarizes meetings with action items.',
    chineseSummary: 'Fireflies.ai 是 AI 会议助手，自动加入 Zoom/Teams/Google Meet 会议录音、转录，并生成会议摘要、待办事项、关键决策。会议结束后几分钟内收到结构化笔记，不需要手动记录。对于每天参加多个会议的顾问、销售、产品经理，每周能节省3-5小时的整理时间。支持按关键词搜索历史会议内容。',
    roleCategories: ['consulting', 'sales', 'product', 'management'],
    functionCategories: ['meeting', 'document-processing'],
    tags: ['meeting notes', 'transcription', 'AI summary', 'Zoom'],
    difficulty: 'beginner',
    requiresCoding: false,
    isOpenSource: false,
    pricingType: 'freemium',
    stars: 0,
    score: 89,
    isActive: true,
    isRelevant: true,
  },
  {
    name: 'Zapier',
    slug: 'zapier',
    officialUrl: 'https://zapier.com',
    githubUrl: null,
    oneLiner: 'No-code automation platform connecting 6000+ apps to automate repetitive workflows.',
    chineseSummary: 'Zapier 是无代码自动化平台，连接6000多个应用，通过简单的"触发-动作"逻辑实现跨平台自动化。例如：收到客户邮件 → 自动创建 CRM 记录 → 发送 Slack 通知。无需编程，适合运营、销售、HR等非技术团队消除重复操作。每月可节省数小时手动数据搬运时间。',
    roleCategories: ['operations', 'sales', 'hr', 'marketing'],
    functionCategories: ['automation', 'crm-sales'],
    tags: ['automation', 'no-code', 'integration', 'workflow'],
    difficulty: 'beginner',
    requiresCoding: false,
    isOpenSource: false,
    pricingType: 'freemium',
    stars: 0,
    score: 87,
    isActive: true,
    isRelevant: true,
  },
  {
    name: 'Notion AI',
    slug: 'notion-ai',
    officialUrl: 'https://www.notion.so/product/ai',
    githubUrl: null,
    oneLiner: 'AI writing and knowledge management assistant built into Notion.',
    chineseSummary: 'Notion AI 是内置在 Notion 中的 AI 助手，能在笔记、文档、数据库中直接调用 AI 进行写作、总结、翻译、改写。不需要切换到其他工具，在当前文档中直接生成内容。特别适合知识工作者整理会议记录、写周报、生成项目说明文档。能节省日常文档处理50%的时间。',
    roleCategories: ['product', 'operations', 'consulting', 'management'],
    functionCategories: ['knowledge-management', 'writing-editing'],
    tags: ['Notion', 'AI writing', 'knowledge base', 'notes'],
    difficulty: 'beginner',
    requiresCoding: false,
    isOpenSource: false,
    pricingType: 'paid',
    stars: 0,
    score: 85,
    isActive: true,
    isRelevant: true,
  },
  {
    name: 'Make (Integromat)',
    slug: 'make-integromat',
    officialUrl: 'https://www.make.com',
    githubUrl: null,
    oneLiner: 'Visual automation platform with advanced data transformation and 1500+ app integrations.',
    chineseSummary: 'Make（原 Integromat）是可视化自动化平台，支持1500多种应用集成，提供比 Zapier 更强的数据处理能力，可以做条件分支、循环、数组操作。特别适合需要复杂数据转换的业务流程，如电商订单处理、多系统数据同步、API集成。免费版额度比 Zapier 更慷慨，适合中小团队。',
    roleCategories: ['operations', 'engineering', 'sales'],
    functionCategories: ['automation', 'data-analysis'],
    tags: ['automation', 'workflow', 'integration', 'visual'],
    difficulty: 'intermediate',
    requiresCoding: false,
    isOpenSource: false,
    pricingType: 'freemium',
    stars: 0,
    score: 86,
    isActive: true,
    isRelevant: true,
  },
  {
    name: 'GitHub Copilot',
    slug: 'github-copilot',
    officialUrl: 'https://github.com/features/copilot',
    githubUrl: null,
    oneLiner: 'AI pair programmer that suggests code and entire functions in real-time inside your editor.',
    chineseSummary: 'GitHub Copilot 是微软/GitHub 出品的 AI 编程助手，在 VS Code、JetBrains 等编辑器中实时提示代码补全和函数生成。基于 GPT-4 训练，理解上下文能自动补全整段函数、单元测试、注释。适合所有编程语言，能节省程序员30-40%的日常编码时间，特别是重复样板代码。每月10美元，企业版提供代码安全扫描。',
    roleCategories: ['engineering'],
    functionCategories: ['coding'],
    tags: ['AI coding', 'VS Code', 'code completion', 'GitHub'],
    difficulty: 'beginner',
    requiresCoding: true,
    isOpenSource: false,
    pricingType: 'paid',
    stars: 0,
    score: 90,
    isActive: true,
    isRelevant: true,
  },
  {
    name: 'Elicit',
    slug: 'elicit',
    officialUrl: 'https://elicit.com',
    githubUrl: null,
    oneLiner: 'AI research assistant that helps find, summarize and extract data from academic papers.',
    chineseSummary: 'Elicit 是专为学术研究设计的 AI 助手，能自动搜索 Semantic Scholar 的数百万篇论文，提取研究方法、样本量、主要结论等关键信息，并生成结构化摘要表格。做文献综述时，过去需要几天手动整理的工作，Elicit 可以在几小时内完成。适合研究人员、学生、咨询顾问做快速文献调研。',
    roleCategories: ['research', 'consulting'],
    functionCategories: ['research-search', 'document-processing'],
    tags: ['research', 'academic', 'literature review', 'AI'],
    difficulty: 'beginner',
    requiresCoding: false,
    isOpenSource: false,
    pricingType: 'freemium',
    stars: 0,
    score: 87,
    isActive: true,
    isRelevant: true,
  },
  {
    name: 'Otter.ai',
    slug: 'otter-ai',
    officialUrl: 'https://otter.ai',
    githubUrl: null,
    oneLiner: 'Real-time meeting transcription and notes with speaker identification and AI summary.',
    chineseSummary: 'Otter.ai 是实时会议转录工具，能在 Zoom/Teams/Google Meet 中实时显示字幕和文字记录，自动识别发言人，会后生成摘要和行动项。支持中英文混录，准确率较高。对于需要频繁开会的销售、咨询、产品团队，能彻底替代手动记录，每周节省2-4小时。免费版有时长限制，付费版支持无限录音和搜索。',
    roleCategories: ['sales', 'consulting', 'product', 'management'],
    functionCategories: ['meeting'],
    tags: ['transcription', 'meeting notes', 'real-time', 'speaker ID'],
    difficulty: 'beginner',
    requiresCoding: false,
    isOpenSource: false,
    pricingType: 'freemium',
    stars: 0,
    score: 85,
    isActive: true,
    isRelevant: true,
  },
  {
    name: 'Beautiful.ai',
    slug: 'beautiful-ai',
    officialUrl: 'https://www.beautiful.ai',
    githubUrl: null,
    oneLiner: 'Smart presentation software with AI design engine that auto-formats slides.',
    chineseSummary: 'Beautiful.ai 是智能演示文稿工具，通过 AI 设计引擎自动保持幻灯片布局美观一致，你只需专注内容。添加内容时，排版自动调整，不需要手动对齐。提供数百个专业模板，适合咨询顾问、产品经理制作专业级汇报材料。对比 PowerPoint，制作相同质量的 PPT 时间减少60%。',
    roleCategories: ['consulting', 'product', 'marketing', 'sales'],
    functionCategories: ['presentation'],
    tags: ['AI PPT', 'design', 'presentation', 'auto-format'],
    difficulty: 'beginner',
    requiresCoding: false,
    isOpenSource: false,
    pricingType: 'freemium',
    stars: 0,
    score: 82,
    isActive: true,
    isRelevant: true,
  },
  {
    name: 'Descript',
    slug: 'descript',
    officialUrl: 'https://www.descript.com',
    githubUrl: null,
    oneLiner: 'AI-powered video and podcast editor that lets you edit audio/video by editing text.',
    chineseSummary: 'Descript 是 AI 视频/播客编辑工具，最大亮点是通过编辑文字稿来编辑音视频——删掉文字就删掉对应的音视频片段，像编辑 Word 文档一样编辑视频。同时支持 AI 配音克隆、自动去除口头禅（嗯、啊）、字幕生成。适合内容创作者、市场团队、培训部门，能将视频剪辑时间压缩70%以上。',
    roleCategories: ['marketing', 'design', 'education'],
    functionCategories: ['video-audio'],
    tags: ['video editing', 'podcast', 'AI audio', 'transcription'],
    difficulty: 'beginner',
    requiresCoding: false,
    isOpenSource: false,
    pricingType: 'freemium',
    stars: 0,
    score: 84,
    isActive: true,
    isRelevant: true,
  },
  {
    name: 'Airtable',
    slug: 'airtable',
    officialUrl: 'https://airtable.com',
    githubUrl: null,
    oneLiner: 'No-code database platform combining spreadsheet ease with relational database power.',
    chineseSummary: 'Airtable 是介于 Excel 和数据库之间的无代码工具，既有表格的直观性，又支持关联字段、多视图（看板、甘特图、日历）和自动化工作流。适合项目管理、CRM、内容日历、招聘追踪等场景，非技术团队即可上手。对比 Excel 更适合多人协作和复杂数据关系，对比专业 CRM 更灵活。最近加入 AI 功能，可自动生成字段内容。',
    roleCategories: ['operations', 'hr', 'product', 'marketing'],
    functionCategories: ['project-management', 'spreadsheet', 'automation'],
    tags: ['no-code', 'database', 'spreadsheet', 'project management'],
    difficulty: 'beginner',
    requiresCoding: false,
    isOpenSource: false,
    pricingType: 'freemium',
    stars: 0,
    score: 83,
    isActive: true,
    isRelevant: true,
  },
  {
    name: 'Claude',
    slug: 'claude-anthropic',
    officialUrl: 'https://claude.ai',
    githubUrl: null,
    oneLiner: "Anthropic's AI assistant with 200K context window, excellent for long document analysis.",
    chineseSummary: 'Claude 是 Anthropic 开发的 AI 助手，拥有200K tokens 超长上下文窗口，能一次处理整本书或完整合同文件。在长文档分析、复杂推理、代码生成方面表现优秀，回答更安全、更少幻觉。适合法务合规（合同审阅）、金融分析（财报解读）、学术研究（文献整理）等需要处理长文本的场景。',
    roleCategories: ['legal', 'finance', 'research', 'consulting', 'engineering'],
    functionCategories: ['document-processing', 'writing-editing', 'research-search'],
    tags: ['AI assistant', 'long context', 'document analysis', 'Anthropic'],
    difficulty: 'beginner',
    requiresCoding: false,
    isOpenSource: false,
    pricingType: 'freemium',
    stars: 0,
    score: 93,
    isActive: true,
    isRelevant: true,
  },
  {
    name: 'ChatGPT',
    slug: 'chatgpt',
    officialUrl: 'https://chat.openai.com',
    githubUrl: null,
    oneLiner: 'OpenAI\'s conversational AI assistant for writing, coding, analysis and more.',
    chineseSummary: 'ChatGPT 是 OpenAI 推出的通用 AI 对话助手，支持写作、代码、分析、翻译、创意等几乎所有文字任务。GPT-4 版本能处理图片、联网搜索、运行代码。对于各岗位职场人，可作为"随身智囊"快速生成草稿、解释概念、优化邮件、总结文档。免费版已足够日常使用，Plus版（20美元/月）解锁GPT-4和插件。',
    roleCategories: ['consulting', 'marketing', 'hr', 'operations', 'management'],
    functionCategories: ['writing-editing', 'research-search', 'document-processing'],
    tags: ['AI assistant', 'GPT-4', 'OpenAI', 'chatbot'],
    difficulty: 'beginner',
    requiresCoding: false,
    isOpenSource: false,
    pricingType: 'freemium',
    stars: 0,
    score: 94,
    isActive: true,
    isRelevant: true,
  },
  {
    name: 'Midjourney',
    slug: 'midjourney',
    officialUrl: 'https://midjourney.com',
    githubUrl: null,
    oneLiner: 'AI image generation tool creating stunning artwork from text descriptions.',
    chineseSummary: 'Midjourney 是目前最强的 AI 图像生成工具之一，通过文字描述生成高质量艺术图像。适合市场品牌团队快速生成概念图、广告素材、社媒配图，设计师用来做灵感探索和原型草图。对比请外包设计师，能节省80%以上的时间和成本。通过 Discord 操作，需要一定学习成本来掌握Prompt技巧。',
    roleCategories: ['design', 'marketing'],
    functionCategories: ['image-design'],
    tags: ['AI image', 'art generation', 'design', 'creative'],
    difficulty: 'intermediate',
    requiresCoding: false,
    isOpenSource: false,
    pricingType: 'paid',
    stars: 0,
    score: 89,
    isActive: true,
    isRelevant: true,
  },
  {
    name: 'Grammarly',
    slug: 'grammarly',
    officialUrl: 'https://www.grammarly.com',
    githubUrl: null,
    oneLiner: 'AI writing assistant for grammar, clarity, tone and style improvements in real-time.',
    chineseSummary: 'Grammarly 是 AI 写作助手，实时检查语法错误、提升表达清晰度、调整语气风格。支持在 Gmail、Docs、Slack、Word 等几乎所有平台使用。对于需要用英文沟通的职场人，能显著提升邮件、报告、提案的专业度。特别适合非英语母语者减少语法错误和表达不地道的问题。免费版已涵盖基础语法检查，商务版提供更丰富的风格建议。',
    roleCategories: ['consulting', 'marketing', 'sales', 'hr'],
    functionCategories: ['writing-editing', 'email'],
    tags: ['writing', 'grammar', 'English', 'proofreading'],
    difficulty: 'beginner',
    requiresCoding: false,
    isOpenSource: false,
    pricingType: 'freemium',
    stars: 0,
    score: 86,
    isActive: true,
    isRelevant: true,
  },
]

export async function POST(req: NextRequest) {
  const authError = requireAdmin(req)
  if (authError) return authError

  try {
    let inserted = 0
    let skipped = 0

    for (const skill of SEED_SKILLS) {
      const existing = await prisma.skill.findUnique({ where: { slug: skill.slug } })
      if (existing) {
        skipped++
        continue
      }
      await prisma.skill.create({ data: skill as any })
      inserted++
    }

    return NextResponse.json({
      ok: true,
      message: `Seed complete: ${inserted} inserted, ${skipped} skipped`,
      inserted,
      skipped,
    })
  } catch (error: any) {
    return NextResponse.json({ ok: false, error: error.message }, { status: 500 })
  }
}
